name: "Translation Request: README"
description: Request a new translation or an update of an existing README translation
title: "[Translation] README to [Language/ISO-Code]"
labels: ["good-first-issue", "translation", "documentation"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make **SwiftyEdit** more accessible! 🌍  
        Use this issue to request a new README translation or an update to an existing one.

  - type: dropdown
    id: language
    attributes:
      label: "Target Language"
      description: "Which language should the README be translated into or updated for?"
      options:
        - German (de)
        - French (fr)
        - Spanish (es)
        - Other (please specify below)
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: "Translation Scope"
      description: "Describe what should be done."
      placeholder: |
        - New translation of README.md
        - Update existing README.de.md to match latest English version
        - Partial update (please specify sections)
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes (optional)"
      description: |
        Helpful context such as:
        - Link or commit reference of the English README
        - Existing translation file status
        - Terminology considerations
      placeholder: "The German README exists but is missing the last two sections added in v1.4.0."
