name: "Translation Request: README"
description: Request a new README translation or an update to an existing one
title: "[Translation] README to [Language/ISO-Code]"
labels: ["good-first-issue", "translation", "documentation"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make **SwiftyEdit** more accessible! 🌍  
        Use this issue to request a **new README translation** or an **update to an existing one**.

  - type: dropdown
    id: language
    attributes:
      label: "Target Language"
      description: "Which language should the README be translated into or updated for?"
      options:
        - German (de)
        - French (fr)
        - Spanish (es)
        - Other (please specify below)
    validations:
      required: true

  - type: textarea
    id: request_type
    attributes:
      label: "What needs to be done?"
      description: "Please specify whether this is a new translation or an update."
      placeholder: |
        Example:
        - Create a new README.de.md based on the current English README.md
        - Update an existing README.fr.md to match the latest English version
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "Additional Notes (optional)"
      description: |
        Helpful context such as:
        - Whether a translated README already exists
        - Reference commit or version of README.md
        - Terminology or style considerations
      placeholder: |
        There is currently no German README.
        Please base the translation on the README.md from commit abc123.
